/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca;

public interface aConstants {
  public final static int ALE = aJNI.ALE_get();
  public final static int LAGER = aJNI.LAGER_get();
  public final static int STOUT = aJNI.STOUT_get();
  public final static int PILSNER = aJNI.PILSNER_get();
  public final static int PILZ = aJNI.PILZ_get();

}
