/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca;

public final class Beers {
  public final static Beers ALE = new Beers("ALE");
  public final static Beers LAGER = new Beers("LAGER", aJNI.LAGER_get());
  public final static Beers STOUT = new Beers("STOUT");
  public final static Beers PILSNER = new Beers("PILSNER");
  public final static Beers PILZ = new Beers("PILZ", aJNI.PILZ_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Beers swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Beers.class + " with value " + swigValue);
  }

  private Beers(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Beers(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Beers(String swigName, Beers swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Beers[] swigValues = { ALE, LAGER, STOUT, PILSNER, PILZ };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

